# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
    -   id: check-yaml
        args: ['--allow-multiple-documents']
        exclude: 'templates/' # exclude files from under helm
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
    -   id: terragrunt_fmt
        args: ['--args=-recursive']
    -   id: terraform_validate
    -   id: terraform_tflint
        args: ['--args=--config=__GIT_WORKING_DIR__/.tflint.hcl']
# TODO: Add another checks: tfsec,checkov...
# tfsec -- too many errors to implement and fix atm, do it later
# TODO: enable helmlint after thinking about adding helm-values...
# -   repo: https://github.com/gruntwork-io/pre-commit
#     rev: v0.1.12 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
#     hooks:
#       - id: helmlint
