apiVersion: v1
kind: Secret
metadata:
  name: klar-secrets
  namespace: klar
type: Opaque
stringData:
  CS_CLIENT_ID: ""
  CS_CLIENT_SECRET: ""
  OKTA_API_TOKEN: ""
  JC_API_KEY: ""
  AUTH_PASSWORD: "changeme"
  JWT_SECRET: "generate-a-random-hex-string-here"
  OPENAI_API_KEY: ""
  SLACK_WEBHOOK_URL: ""
