apiVersion: v1
kind: Service
metadata:
  name: device-normalizer
  namespace: device-normalizer
  labels:
    app: device-normalizer
spec:
  type: ClusterIP
  selector:
    app: device-normalizer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
