apiVersion: v1
kind: Service
metadata:
  name: klar-device-normalizer
  namespace: klar
  labels:
    app: klar-device-normalizer
spec:
  type: ClusterIP
  selector:
    app: klar-device-normalizer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
