terraform {
  source = "../../../..//modules/klar-assets"
}

include {
  path = find_in_parent_folders()
}

inputs = {
  region              = "us-east-2"
  environment         = "neutral"
  namespace           = "klar-assets"
  OKTA_OIDC_CLIENT_ID        = "AQICAHju9UgRfcgZoL2GAZMAn9eRswlN9J4gDefqHVnf1n+EUwHgkbrZkmKFG8+mEC1v/q3/AAAAczBxBgkqhkiG9w0BBwagZDBiAgEAMF0GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMG0VDur6KaWRQhC9eAgEQgDBtY0pW07twbOVu1Un025QRZgG3AajE7hoIumohFCNIhkgzxwoWy7yq/8PRu8mG+1g="
  OKTA_OIDC_CLIENT_SECRET    = "AQICAHju9UgRfcgZoL2GAZMAn9eRswlN9J4gDefqHVnf1n+EUwF5PLEXAJhtrfNg6Ygzfh/4AAAAozCBoAYJKoZIhvcNAQcGoIGSMIGPAgEAMIGJBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDIh47l9tc4RiyfuxaAIBEIBc6c55K18tISEbuGfXjjK+QjNLZ+TFNinA1WrR5ZWWul8teYrQlDF/stzpOx2DhpRtKH0l3LC9z1jnQlb/E35Ewp2CGVtjjMfmUzmy0bqBDM56donPu+9Qls4yq3A="
  OKTA_API_TOKEN      = "AQICAHju9UgRfcgZoL2GAZMAn9eRswlN9J4gDefqHVnf1n+EUwHcu7qe0qTM8DVoMl4FKRBsAAAAijCBhwYJKoZIhvcNAQcGoHoweAIBADBzBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDOWG07puCbth+2GVjwIBEIBG/EJ6Tz36hsxQ09ElQng6Q7tXChQ9Qwt0M0w+pRdVZvCuc8wSLzHF2C/U2svFBzgYJw4kS/KniKNE8bm4fSskli9B+Ma/oA=="
  JC_API_KEY          = "AQICAHju9UgRfcgZoL2GAZMAn9eRswlN9J4gDefqHVnf1n+EUwHfWqwro6PoZpsjM8G4xElvAAAAiDCBhQYJKoZIhvcNAQcGoHgwdgIBADBxBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLnsb4Mecyu5WRC5TQIBEIBEPyO88NOCdaTvKUsGdF0tPQSMhunKakdn10Cr3Sl69Ftf5j8jEmjxjy/LDDkUMp/TLlnKZQV0OTrUp5O+OTyoK8BCeeE="
  AUTH_PASSWORD       = "AQICAHju9UgRfcgZoL2GAZMAn9eRswlN9J4gDefqHVnf1n+EUwEwRafTdjNiOWdgS/iI6npqAAAAbDBqBgkqhkiG9w0BBwagXTBbAgEAMFYGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/meZbreYQqLTqA8cAgEQgCm7xslTiLmvtp3pY3nK0KHZSDo2sAVrHgHkGqr+DWql5ZvE8tgl3pu/Gg=="
  OPENAI_API_KEY      = "AQICAHju9UgRfcgZoL2GAZMAn9eRswlN9J4gDefqHVnf1n+EUwFJIs8/oPacawOOdvBT/0fiAAABCTCCAQUGCSqGSIb3DQEHBqCB9zCB9AIBADCB7gYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzC6f1Hj9T+jSRdLdMCARCAgcDlny/O9diECKgf8mgOuMmOrB3I2ZcQWTkMoPdZgsq7TY/tRQlALBEfu6vbjfbfyQiGjL/30YkLDfxLYt1fXFDLE7KscZUqFzZxCDXXhmfQJF37t+JCPtt5r6ewH9+sBcbLcl5MgN3Icy8iTULQMB10q23zCiwgImVyKNvWEryuv1t6b/aEJIw7+zH0hg6wABBeCQLPWc6Bioum8ae8OpoZDNSwcltskjoh+kmzOZIikjVJsDCwe9VLK21oFVXPTPQ="
  SLACK_WEBHOOK_URL   = "AQICAHju9UgRfcgZoL2GAZMAn9eRswlN9J4gDefqHVnf1n+EUwFdBfgoqvoUAO3uqXhF3xCQAAAAsjCBrwYJKoZIhvcNAQcGoIGhMIGeAgEAMIGYBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDEo0O1P9lpRhVmyADQIBEIBrVrmJ7LvvhrXz4VuAZ8rALd6k71PYrYso1tSdVd7+b2iJYCzdo2gXqVHXRuEnfWPbbiY+6VE3+LbSYSv6x3ke7P9A3ajLbOBa+Lurh/rkK1kcGYDqH4ICtHVStRbfyY3n1qdGVp43jaK4SZQ="
  }
