name: Plan changes

on: pull_request

jobs:
  plan:
    concurrency:
      group: "terraform-${{ matrix.environment }}"
    strategy:
      fail-fast: false
      matrix:
        environment: [neutral] # NOTE: change to your environments
    name: Plan Terraform changes
    runs-on: [self-hosted, default]
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: '${{ secrets.ORG_SSH_KEY }}'
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'klar-mx/github-actions'
          ref: 'v2'
          path: '.actions'
          ssh-key: '${{ secrets.ORG_SSH_KEY }}'
      - uses: ./.actions/plan_infra
        with:
          environment: '${{ matrix.environment }}'
          post_results: 'true'